import express from 'express';
import { 
  getRiskCases, 
  getRiskCaseById, 
  applyRiskCaseAction,
  getBatches,
  createCustodyEvent
} from '../services/dataStore.js';
import riskEngine from '../services/riskEngine.js';
import { emitRiskAlert } from '../services/eventBus.js';
import { authenticateToken, authorizeRoles, ROLES } from '../middleware/auth.js';

const router = express.Router();

/**
 * GET /api/risk-cases
 * Retrieves inspection risk cases generated by the AI Risk Engine.
 * STRICT RBAC: Accessible only to Compliance Inspectors, Government Authorities,
 * and affected facility operators (scoped to their own facility).
 */
router.get('/', authenticateToken, authorizeRoles(
  ROLES.COMPLIANCE_INSPECTOR,
  ROLES.GOVERNMENT_AUTHORITY,
  ROLES.HOSPITAL_AUTHORITY,
  ROLES.TREATMENT_FACILITY
), async (req, res) => {
  try {
    const { status, min_score, minScore, inspector_id, inspectorId } = req.query;
    const user = req.user;

    let cases = await getRiskCases({
      status,
      minScore: min_score || minScore,
      inspectorId: inspector_id || inspectorId
    });

    // Facility scoping for facility operators
    if (user.role === ROLES.HOSPITAL_AUTHORITY && user.facility_id) {
      cases = cases.filter(c => c.batch?.hospital_id === user.facility_id);
    } else if (user.role === ROLES.TREATMENT_FACILITY && user.facility_id) {
      cases = cases.filter(c => c.batch?.assigned_cbwtf_id === user.facility_id);
    }

    res.status(200).json({
      count: cases.length,
      filters: {
        status: status || null,
        min_score: min_score || minScore || null,
        inspector_id: inspector_id || inspectorId || null
      },
      risk_cases: cases
    });
  } catch (err) {
    console.error('[RiskCases Route] GET / error:', err);
    res.status(500).json({ error: 'Failed to fetch risk cases', message: err.message });
  }
});

/**
 * POST /api/risk-cases/run-sla-check
 * Triggers batch SLA evaluation across all active batches and creates cases for breaches.
 * STRICT RBAC: Regulators and Inspectors only.
 */
router.post('/run-sla-check', authenticateToken, authorizeRoles(
  ROLES.COMPLIANCE_INSPECTOR,
  ROLES.GOVERNMENT_AUTHORITY
), async (req, res) => {
  try {
    const result = await riskEngine.runSlaCheck();
    res.status(200).json({
      message: 'SLA compliance check completed successfully.',
      ...result
    });
  } catch (err) {
    console.error('[RiskCases Route] POST /run-sla-check error:', err);
    res.status(500).json({ error: 'Failed to run SLA compliance check', message: err.message });
  }
});

/**
 * POST /api/risk-cases/test-broken-chain
 * Simulates an out-of-order broken chain-of-custody event:
 * (e.g. jumps directly from GENERATION to TREATMENT, skipping COLLECTION and TRANSPORT),
 * calculates composite risk score (>= 85), creates BROKEN_CHAIN_OF_CUSTODY case,
 * and emits real-time WebSocket alert.
 * STRICT RBAC: Regulators and Inspectors only.
 */
router.post('/test-broken-chain', authenticateToken, authorizeRoles(
  ROLES.COMPLIANCE_INSPECTOR,
  ROLES.GOVERNMENT_AUTHORITY
), async (req, res) => {
  // Production environment safeguard: disable in production unless demo endpoints explicitly allowed
  if (process.env.NODE_ENV === 'production' && process.env.ALLOW_DEMO_ENDPOINTS !== 'true') {
    return res.status(404).json({
      error: 'Not Found',
      message: 'Test simulation endpoints are disabled in production environment.'
    });
  }

  try {
    const { batch_id, stage } = req.body || {};
    const batches = await getBatches();
    let targetBatch = batch_id 
      ? batches.find(b => b.id === batch_id || b.batch_code === batch_id) 
      : batches.find(b => b.status === 'GENERATED' || b.status === 'COLLECTED') || batches[0];

    if (!targetBatch) {
      return res.status(404).json({ error: 'No test batch found to simulate broken chain.' });
    }

    const skippedToStage = stage || 'TREATMENT';

    // Structured Audit Log for Security & Compliance Monitoring
    console.warn(
      `[SECURITY AUDIT] Test broken chain endpoint triggered by ${req.user.name} (${req.user.email}, Role: ${req.user.role}). ` +
      `Simulated skip to stage '${skippedToStage}' on batch '${targetBatch.batch_code}' at ${new Date().toISOString()}.`
    );

    // Directly log out-of-order stage bypassing regular sequence
    await createCustodyEvent(targetBatch.id, {
      stage: skippedToStage,
      quantity_at_stage_kg: targetBatch.quantity_kg,
      notes: `SIMULATED AUDIT ANOMALY: Directly jumped to '${skippedToStage}' stage by ${req.user.name} (${req.user.role}), skipping required intermediate collection & transit protocols.`,
      force: true,
      bypass_validation: true
    });

    // Run AI Risk Engine evaluation
    const evalResult = await riskEngine.evaluate(targetBatch.id);

    if (evalResult?.riskCase) {
      emitRiskAlert(evalResult.riskCase);
    }

    res.status(201).json({
      message: `Broken chain-of-custody anomaly successfully simulated on batch ${targetBatch.batch_code}.`,
      batch_code: targetBatch.batch_code,
      attempted_stage: skippedToStage,
      risk_score: evalResult.riskScore,
      risk_case: evalResult.riskCase,
      triggers: evalResult.triggers
    });
  } catch (err) {
    console.error('[RiskCases Route] POST /test-broken-chain error:', err);
    res.status(500).json({ error: 'Failed to simulate broken chain anomaly', message: err.message });
  }
});

/**
 * GET /api/risk-cases/:id
 * Retrieves detailed inspection case record including triggers, linked batch, and audit history.
 * STRICT RBAC & SCOPING: Only Inspector, Regulator, and affected facility operator can view.
 */
router.get('/:id', authenticateToken, authorizeRoles(
  ROLES.COMPLIANCE_INSPECTOR,
  ROLES.GOVERNMENT_AUTHORITY,
  ROLES.HOSPITAL_AUTHORITY,
  ROLES.TREATMENT_FACILITY
), async (req, res) => {
  try {
    const { id } = req.params;
    const user = req.user;
    const riskCase = await getRiskCaseById(id);

    if (!riskCase) {
      return res.status(404).json({
        error: 'Not Found',
        message: `Risk Case with ID or Code '${id}' was not found.`
      });
    }

    // Scoping check for facility authorities
    if (user.role === ROLES.HOSPITAL_AUTHORITY && user.facility_id && riskCase.batch?.hospital_id && riskCase.batch.hospital_id !== user.facility_id) {
      return res.status(403).json({
        error: 'Forbidden: Scoped facility access violation',
        message: 'Hospital Authority cannot access risk cases from another facility.'
      });
    }

    if (user.role === ROLES.TREATMENT_FACILITY && user.facility_id && riskCase.batch?.assigned_cbwtf_id && riskCase.batch.assigned_cbwtf_id !== user.facility_id) {
      return res.status(403).json({
        error: 'Forbidden: Scoped facility access violation',
        message: 'Treatment facility cannot access risk cases assigned to another facility.'
      });
    }

    res.status(200).json({ risk_case: riskCase });
  } catch (err) {
    console.error('[RiskCases Route] GET /:id error:', err);
    res.status(500).json({ error: 'Failed to fetch risk case details', message: err.message });
  }
});

/**
 * POST /api/risk-cases/:id/action
 * Allows an assigned Compliance Inspector or Regulator to take action on a risk case.
 * STRICT RBAC: Only COMPLIANCE_INSPECTOR and GOVERNMENT_AUTHORITY can apply enforcement actions.
 */
router.post('/:id/action', authenticateToken, authorizeRoles(
  ROLES.COMPLIANCE_INSPECTOR,
  ROLES.GOVERNMENT_AUTHORITY
), async (req, res) => {
  try {
    const { id } = req.params;
    const { action, notes } = req.body || {};

    if (!action) {
      return res.status(400).json({
        error: 'Missing action parameter',
        message: 'Field "action" is required. Allowed actions: INVESTIGATE, ESCALATE, REQUEST_EVIDENCE, RESOLVE'
      });
    }

    const performerInspectorId = req.user.id;

    const result = await applyRiskCaseAction(id, {
      action,
      notes,
      inspectorId: performerInspectorId
    });

    if (result.error) {
      const statusCode = result.error === 'NOT_FOUND' ? 404 : 400;
      return res.status(statusCode).json({ error: result.error, message: result.message });
    }

    // Broadcast case action via EventBus -> Socket.IO
    emitRiskAlert(result.riskCase);

    res.status(200).json({
      message: `Action '${action}' applied to Risk Case successfully.`,
      risk_case: result.riskCase,
      action_log: result.actionLog
    });
  } catch (err) {
    console.error('[RiskCases Route] POST /:id/action error:', err);
    res.status(500).json({ error: 'Failed to apply risk case action', message: err.message });
  }
});

export default router;
